name: joystick_example
description: A joystick widget for your apps. This widget has four arrow buttons and it is also draggable.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  joystick: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

